ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS location TEXT,
  ADD COLUMN IF NOT EXISTS land_size TEXT,
  ADD COLUMN IF NOT EXISTS soil_type TEXT,
  ADD COLUMN IF NOT EXISTS irrigation TEXT,
  ADD COLUMN IF NOT EXISTS current_crop TEXT,
  ADD COLUMN IF NOT EXISTS crop_sown_date DATE,
  ADD COLUMN IF NOT EXISTS farming_goal TEXT,
  ADD COLUMN IF NOT EXISTS onboarding_completed BOOLEAN NOT NULL DEFAULT false;